project:
  type: website
  output-dir: docs

website:
  title: "Xavier Clemente Garc√≠a Cevallos"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: CV
        menu:
          - href: English.qmd
            text: English
          - href: Spanish.qmd
            text: Spanish
      - text: More
        menu:
          - href: Courses.qmd
            text: Courses
          - href: Divulgation.qmd
            text: Divulgation
    right: 
      - icon: twitter
        href: https://x.com/clementegarcC
      - icon: linkedin
        href: https://www.linkedin.com/in/xavier-clemente-garc%C3%ADa-cevallos-b4727a206/
      - icon: github
        href: https://github.com/xavierclementegarcia 
      - text: '<img src="https://investigacion.udca.edu.co/wp-content/uploads/2018/04/cvlac.svg" alt="CLVAC" style="width: 20px; height: 20px;">'
        href: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0002018236
      - text: '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/ORCID_iD.svg/1024px-ORCID_iD.svg.png" alt="ORCID" style="width: 20px; height: 20px;">'
        href: https://orcid.org/0000-0002-3284-2363
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

